sistemasiq/TurboERP_backend

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCOrden.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/FacturaFinalVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaFinalService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaFinal.java

http://localhost:8181/comercial/facturafinal/cliente/{id}/{moneda}
DAO---RM---JDBC
POJO:FacturaFinalVista
Service----Logica
WS
Actualizacion campo PA tipo_cambio
JDBC

Actualizacion de WS que consulta facturas pendientes de pago

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/ConceptosNotasCreditoDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/ConceptosNotasCreditoRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCConceptosNotasCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/ConceptosNotasCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSConceptosNotasCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/ConceptosNotasCreditoService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaConceptosNotasCredito.java

Se creo el modelo, las clases en  el paquete DAO, en el paquete Service y en REST
GET comercial/conceptosnotascredito consultar()

Se creo el servicio web que consulte los conceptos de notas de credito

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaFinalService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaFinal.java

/comercial/facturafinal/folio
REST
service
Logica
JDBC
RM
DAO

Se agregó WS buscar factura final por folio

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaVariosDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaVariosRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaVarios.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/FacturaVarios.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaVarios.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaVariosService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaVarios.java

GET   /comercial/facturavarios/cliente/{id}/{moneda}
Se agrego al modelo y al RM el atributo estado, se creo en el DAO el metodo que consulta facturas_varios por id del cliente y moneda de la factura, tambien se agrego en el paquete service. Se implemento el metodo en el JDBC y se creo su controlador en WSFacturaVarios. Todo OK 👌

Se agrego servicio web que consulte FACTURAS_VARIOS por id del cliente y moneda

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturasDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturasRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturas.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/Facturas.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturas.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturasService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturas.java

Se agrego el ws que consulta los datos generales de factura_final y factura_varios, unidos en FACTURAS_V
*WS que consulta todas las facturas de un cliente que tengan saldo

Se agrego el ws que consulta los datos generales de factura_final y

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/DepositoRecibidoDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/DepositoRecibidoRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/DepositoRecibidoVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCDepositoRecibido.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/DepositoRecibido.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/DepositoRecibidoVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSDepositoRecibido.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/DepositoRecibidoService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaDepositoRecibido.java

Se obtienen los Depósitos Recibidos por fecha, pero ahora se hace un filtrado según el estado del Deposito, donde NA, muestra los No Aplicados, A los aplicados y * todos los Depósitos.

Se modificó el WS de consulta de Depositos Recibidos

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCCotizacion.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/ActividadAutorizadaFacturaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCActividadAutorizada.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/general/ActividadAutorizadaFactura.java

Se optimizó consulta de cotizaciones con actividades pendientes de
autorizar por id de orden

GET /comercial/cotizacion/sinautorizar/orden/{id}

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/OrdenesRequisicionesRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/proveedores/ConsultaRequisicionesRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/general/OrdenesRequisiciones.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/proveedores/ConsultaRequisiciones.java

Se agregaron atributos en la clase POJO de Consulta requisiciones y se agregaron en la clase Consulta Requisiciones RM.
Se agregaron atributos en la clase POJO de OrdenesRequisiciones y se agregaron en la clase Ordenes Requisiciones RM.

Cambios en clase POJO y RM de las clases Consulta Requisiciones y Ordenes Requesiciones.

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/ActividadAutorizadaDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCActividadAutorizada.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCOrden.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCSolicitudDesautorizacionAA.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/OrdenDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/SolicitudDesautorizacionAADAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/general/ActividadAutorizadaService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/general/LogicaSolicitudBajaAA.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/general/SolicitudBajaAAService.java

PUT /general/solicitudbaja-aa/{id}/resultado

Actualización de importe_baja y autorizado al dar de baja o desautorizar actividades autorizadas

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCPagos.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/PagosDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/DocumentoAplicarPago.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/FacturasPagadas.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/OrdenesporFactura.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSPagos.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaPagos.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/PagosService.java

WS que reciba el documento de Aplicación de Pagos y ejecute el PA para la inserción en pagos, pagos_detalle, actualice importe de facturas final, así como la actualización de importes de las ordenes de cada una de las facturas.

WS que reciba el documento de Aplicación de Pagos

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/proveedores/ConsultaRequisicionesRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaDocFacturaFinal.java

Comente el método de crear de la clase LogicaDocFacturaFinal por errores.   Cambio en la clase ConsultaRequesicionesRM.

Comente el metodo de crear de la clase LogicaDocFacturaFinal por errores.   Cambio en la clase ConsultaRequesicionesRM.

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCNotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/NotaCreditoDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/NotaCreditoRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/DocumentoAplicarNotasCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/FacturasJSON.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/NotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSNotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaNotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/NotaCreditoService.java

ws-nota-credito : WS Nota Credito
POST /comercial/notacredito/aplicar-notaCredito
Se creo la clase de DocumentoAplicarNotasCredito y FacturasJSON que tiene los tributos necesarios para inserta en notas de credito.
Se modifico la clase POJO y RM de NotasCredito de acuerdo a los cambios en las columnas en la BD.
Se agrego el metodo de AplicarNotasCredito en el servicio y DAO

WS que inserta en la tabla NOTAS_CREDITO

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/proveedores/ConsultaRequisicionesRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/proveedores/ConsultaRequisiciones.java

Se agrego el atributo tipo string no_aplica_cuarentena

Cambios en clase POJO ConsultaRequesiciones y clase RM.

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/ClienteDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/ClienteService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaFinalService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaFinal.java

- Cambio al WS Factura Final de @RequestParam estado a @PathVaribale  
- WS CLIENTE devuelve el tipo del cliente por un id de cliente
- cambio de HttpStatus al método buscarFacturaFolio

Cambios a Factura Final y a Clientes

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/CatalogoCuentasDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/CatalogoCuentasRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCCatalogoCuentas.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/CatalogoCuentas.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSCatalogoCuentas.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/CatalogoCuentasService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaCatalogoCuentas.java

se crearon las clases para el WS CatalogoCuentas consultar

WS CatalogoCuentas consultar

---

TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSCatalogoCuentas.java

Agregué ruta del WS CatalogoCuentas

Ruta WS CatalogoCuentas

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/FacturaFinalVista.java

Se quitaron campos FACTURA_FINAL_id_sus y folio_fiscal_sus

Se actualizó vista y RM de la factura final

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/ConceptosNotasCreditoDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/ConceptosNotasCreditoVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCConceptosNotasCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/ConceptosNotasCreditoVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSConceptosNotasCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/ConceptosNotasCreditoService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaConceptosNotasCredito.java

Se agrego la clase de ConceptosNotasCreditoVista junto con su RM y se añadió el WS para buscar una nota de crédito por su id.

Se agrego ConceptosNotasCreditoVista-RM y WS buscar.

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/ConceptosNotasCreditoDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCConceptosNotasCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSConceptosNotasCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/ConceptosNotasCreditoService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaConceptosNotasCredito.java

Se agrego el WS para crear un nuevo concepto de nota de crédito y se modifico el WS de consultar los conceptos de notas de crédito, para que fuera sobre la vista.

WS Crear un nuevo concepto de nota de crédito y cambio en WS consultar sobre la vista

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/ActividadesFFDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/ActividadesFFVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCActividadesFF.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/ActividadesFFVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/FacturaFinalVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaFinalService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaFinal.java

/comercial/facturafinal/{id}/actividades

Creación de WS para consulta de Actividades de Factura Final en base al ID de la factura

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCOrden.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/general/WSOrden.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/general/LogicaOrdenService.java

orden
/general/ordenes/{id}/facturas

Correción de código de estado en WS que regresa las facturas de una

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/NotaCreditoRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/NotaCreditoVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/DocumentoAplicarNotasCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/NotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/NotaCreditoVista.java

Se agrego el atributo de fechas al POJO DocumentoAplicarNotasCredito y se agrego el atributo importe_total al POJO NotaCredito y a
NotaCreditoRM

Agregación de atributos faltantes para Notas de Crédito

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/DatosTimbradosDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/DatosTimbradosRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCDatosTimbrados.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/DatosTimbrados.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/FacturaFinalVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSDatosTimbrados.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/timbrado/WSTimbrado.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/DatosTimbradosService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaFinalService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaDatosTimbrados.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/timbrado/LogicaTimbrado.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/timbrado/TimbradoService.java

-Actualizar el Tipo_Cambio del día
-Actualizar el estado de la factura a T
-Insertar en DatosTimbrados
-Actualizar el campo DATOS_TIMBRADOS_id en FF

Avances WS timbrado, se implementó funcionalidad de:

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaFinalService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaFinal.java

GET /comercial/facturafinal/{tipo}/ultima

WS regrese ultima factura en estado I por tipo (T/X)

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCActividadAutorizada.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/DocumentoFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaFinalService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaFinal.java

Reverts sistemasiq/TurboERP_backend#74

Revert "SW Crear Factura Varios"

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCNotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/NotaCreditoDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/NotaCreditoVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/NotaCreditoVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSNotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaNotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/NotaCreditoService.java

Cambio el modelo de NotaCreditoVista de acuerdo a los nuevos atributos en la vista de la BD y se cambio el tipo de retorno para los metodos de
crear, buscar y consultar una nota de credito de tipo NotaCredito a
NotaCreditoVista.

Modificaciones en los atributos del modelo NotaCreditoVista 

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCActividadesFF.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/timbrado/JDBCTimbrado.java

Actualizacion de WS que regresa Actividades de Factura Final, solo

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaVariosDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaVarios.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaVarios.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaVariosService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaVarios.java

WS consulta de Factura Varios por estado, cambio de estado en la baja de factura varios

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaVariosVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/comercial/FacturaVariosVista.java

Se agregó a la vista de factura varios el tipo y numero de la factura varios sustitucion

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaFinalDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/FacturaVariosDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCFacturaVarios.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSFacturaVarios.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/timbrado/WSTimbrado.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaFinalService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/FacturaVariosService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaVarios.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/timbrado/LogicaTimbrado.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/timbrado/TimbradoService.java

WS para Cancelar de FacturaFinal llamando PA Cancelar Factura Final
DELETE /comercial/facturafinal/{id}/cancelacion/{numUsuario}
WS para Baja de FacturaFinal llamando PA Baja Factura Final
DELETE /comercial/facturafinal/{id}/baja/{numUsuario}
Remover WS de cancelación anterior de Factura Varios
Remover WS de cancelación anterior de Factura Final
WS de timbrado de FacturaFinal y FacturaVarios reestructurado para separar afectaciones de BD y de la API
PUT /comercial/facturafinal/{id}/timbrado
PUT /comercial/facturavarios/{id}/timbrado

 WS de timbrado en FacturaFinal y FacturaVarios

---

TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaFinal.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaFacturaVarios.java

Al timbrar considerar solo actualizar el tipo_cambio si la moneda es diferente de MXN

Modificación WS FF Y FV 

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCPagos.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/PagosDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/timbrado/WSTimbrado.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaPagos.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/PagosService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/timbrado/LogicaTimbrado.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/timbrado/TimbradoService.java

Tambien se reajustaron nombres de los métodos

Avance WS Timbrado de Pagos

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/InsatisfaccionClienteDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/InsatisfaccionClienteVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/JDBCInsatisfaccionCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/InsatisfaccionCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/InsatisfaccionClienteVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/calidad/WSInsatisfaccionCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/general/WSOrden.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/InsatisfaccionClienteService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/LogicaInsatisfaccionCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/general/LogicaOrdenService.java

Un WS para obtención de Insatisfacciones con base al folio y otro para
la actualización de una insatisfacción
Modificación del modelo insatisfaccionClienteVista y su RM

Creacion de 2 WS y modificacion de un modelo 

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCNotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/NotaCreditoDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/calidad/WSInsatisfaccionCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSNotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaNotaCredito.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/NotaCreditoService.java

Tambien se agregó un WS para buscar una Nota de Credito por número.

Cambio de estructura de URI de insatisfacciones

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/ActividadAutorizadaDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCActividadAutorizada.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/general/DocumentoAAPedidoPrepedido.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/general/WSActividadAutorizada.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/general/ActividadAutorizadaService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/general/LogicaActividadAutorizada.java

para mejorar la forma en que se realizan las actualizaciones de las actividades, así como considerar actualizar los importes_autorizados en la orden al regularizar actividades

Implementar PA en regularización de AA

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/InsatisfaccionClienteDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/JDBCInsatisfaccionCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/SeguimientoInsatisfaccionVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/SeguimientoInsatisfaccionVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/calidad/WSInsatisfaccionCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/InsatisfaccionClienteService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/LogicaInsatisfaccionCliente.java

-Actualización WS de crear seguimiento para regresar objecto
-WS para actualizar campo alfresco_ids de la tabla SEGUIMIENTO_INSATISFACCION

WS Seguimiento Insatisfacción

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/InsatisfaccionClienteDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/InsatisfaccionClienteVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/JDBCInsatisfaccionCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/InsatisfaccionClienteVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/calidad/WSInsatisfaccionCliente.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/InsatisfaccionClienteService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/LogicaInsatisfaccionCliente.java

Se agregaron campos a servicios de busqueda y consulta anteriores:
-estado, 
-procede_garantia,
-dias_antiguedad

WS para aplicar filtros de consulta de insatisfacciones

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/SeguimientoInsatisfaccionVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/SeguimientoInsatisfaccionVista.java

Modificación WS que busca seguimientos para regresar el listado JSON de

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/DetalleGarantiaDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/DetalleGarantiaVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/EncabezadoGarantiaDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/EncabezadoGarantiaVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/GarantiaDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/GarantiaVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/JDBCDetalleGarantia.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/JDBCEncabezadoGarantia.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/JDBCGarantia.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/JDBCSubindiceGarantia.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/SubindiceGarantiaDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/calidad/SubindiceGarantiaVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/DetalleGarantiaVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/DocumentoDetalleGarantia.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/EncabezadoGarantiaVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/GarantiaVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/calidad/SubindiceGarantiaVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/calidad/WSDetalleGarantia.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/calidad/WSGarantias.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/DetalleGarantiaService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/GarantiaService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/LogicaDetalleGarantia.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/calidad/LogicaGarantia.java

***WS para asignar detalles a las actividades de garantia, 
***WS de consulta de encabezados, 
-detalles y 
-subindices por garantia,
**WS que busca garantia
WS que recuperar cantidad de encabezados de una garantia

WS de garantia

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/CotizacionDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/comercial/JDBCCotizacion.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/comercial/WSCotizacion.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/CotizacionService.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/comercial/LogicaCotizacion.java

/comercial/cotizacion/sinautorizar/cliente/{id}/{moneda}
La consulta estaba incompleta

Corrección a WS que regresa cotizaciones pendientes de autorizar por id de cliente y moneda

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/diagnostico/JDBCDetalleDiagnostico.java

/diagnostico/detallediagnostico/autorizados/diagnostico/{id}

Correción WS afectado por los cambios a la estructura de la BD

---

TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCOrden.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/JDBCOrdenInicioTrabajo.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/OrdenInicioTrabajoDAO.java
TurboERP_backend/src/main/java/com/turbomaquinas/DAO/general/OrdenInicioTrabajoVistaRM.java
TurboERP_backend/src/main/java/com/turbomaquinas/POJO/general/OrdenInicioTrabajoVista.java
TurboERP_backend/src/main/java/com/turbomaquinas/REST/general/WSOrdenInicioTrabajo.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/general/LogicaOrdenInicioTrabajo.java
TurboERP_backend/src/main/java/com/turbomaquinas/service/general/OrdenInicioTrabajoService.java

WS que regrese OIT aplicando filtros
WS que regrese años de OIT
WS que cancele OIT y sus actividades

WS para pantalla de consulta de OIT
